baseURL = 'https://antonioemateus.pages.dev/'
languageCode = "pt-BR"
defaultContentLanguage = "pt-BR"
title = 'Antônio & Mateus'
theme = 'lynx'

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "Antônio & Mateus"
  headline = "Conheça um pouco mais sobre os gêmeos Antônio & Mateus."
  image = "antonioemateus_profile.jpg"

  links = [
    { email = "mailto:triplopapa@duck.com" },
    { tiktok = "https://tiktok.com/@antonioemateus"},
    { youtube = "https://youtube.com/antonioemateus"},
    { link = { href = "./contato", text = "Publicidade & Parcerias" } }
  ]

[services]
  [services.googleAnalytics]
    id = 'GTM-56GD6BLJ'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"


